### PR TITLE
Adds support for kwargs from version 1.1

### PR DESCRIPTION
**Pull request by Raahul-Singh**
This probably needs a comment explaining the pop

### CODE REVIEW

**Comment by Raahul-Singh** [comment]
@Cadair this passes tests locally. I wanted minimal changes to the code.

**Comment by Cadair** [comment]
:+1: on the comment, I think this should be good otherwise.

**Comment by Raahul-Singh** [comment]
>  on the comment, I think this should be good otherwise.

Anything more required, before we merge it?

**Comment by Cadair** [comment]
add an inline comment explaining why it's there and maybe a simple test?

**Comment by Raahul-Singh** [comment]
This works?

**Comment by Cadair** [comment]
Why is there no CI on the 1.0 branch. *grumble*

**Pull request merged**
